### ISSUE TITLE
Manual Installation of Packages vs. install.packages() 

### ISSUE THREAD

**Issue by lxwrght** [nguyens7/MSU_Data_Science#1]
I would recommend adding the install.packages() function to the code instead of manually installing packages via the 'Files/Plots' console. A lot of workshop attendees had difficulty or did not manually add the packages (or just added one), in which case they could not run the code. Besides installing R, it was the main issue folks needed help with, and adding install.packages() might help streamline the issue. I'd recommend adding:

# Install packages
install.packages('tidyverse')
install.packages('babynames')
install.packages('cowplot')

It might not be necessary, but thought it might be helpful. Great workshop, by the way!

**Comment by nguyens7** [comment]
Thanks for the suggestion! The reason why I didn't add it to begin with was to prevent people from reinstalling packages if they ran the whole script but I see your point.  I added the install packages to the script but commented them out to prevent people from accidentally reinstalling packages.

**Comment by lxwrght** [comment]
Great idea!

**Comment by lxwrght** [comment]
Came across this code that checks to see if you have a package installed, and if not, will install it. If you do, it will still load the library.

if(!require(_package-name_)) {
  install.packages("_package-name_"); 
  require(_package-name_)
}

Require is synonymous with library (but for some reason won't work if you use the library function).

Edit: spelling/grammar mistakes
